#!/bin/bash

if [ -f "$HOME/.cache/wal/colors.sh" ]; then
	source "$HOME/.cache/wal/colors.sh"
	bspc config normal_border_color ${color7}
	bspc config focused_border_color ${color2}
	bspc config presel_feedback_color ${color2}
fi


~/.cfg/bin/bootstrap.sh ~/.config/bspwm/sxhkdrc

bspc monitor -d 1 2 3 4 5

bspc config border_width          2
bspc config window_gap            12
bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Screenkey manage=off
bspc rule -a NNN state=floating
