#!/bin/bash

if [ "$INSTALL" = 1 ]; then
	git clone https://github.com/mattmc3/antidote.git ~/.local/share/antidote
fi

function hist {
	history 1 | fzf -1 --tac --no-sort ${1:+-q"$1"} | cut -d' ' -f 4-
}

export HISTSIZE=50000
export SAVEHIST=50000

setopt extended_history
setopt hist_expire_dups_first
setopt hist_find_no_dups
setopt hist_ignore_all_dups
setopt hist_ignore_dups
setopt hist_ignore_space
setopt hist_save_no_dups
setopt hist_verify
setopt inc_append_history
setopt share_history

setopt interactivecomments

bindkey -e

bindkey -s '^z' '^Qfg^M'
bindkey -s '^[l' '^Qls^M'
bindkey '^ ' autosuggest-accept

autoload -U edit-command-line
zle -N edit-command-line
bindkey '^[e' edit-command-line
bindkey '^[m' copy-prev-shell-word

autoload -U up-line-or-beginning-search
zle -N up-line-or-beginning-search

bindkey -M emacs "^[[A" up-line-or-beginning-search
if [[ -n "${terminfo[kcuu1]}" ]]; then
  bindkey -M emacs "${terminfo[kcuu1]}" up-line-or-beginning-search
fi

autoload -U down-line-or-beginning-search
zle -N down-line-or-beginning-search

bindkey -M emacs "^[[B" down-line-or-beginning-search
if [[ -n "${terminfo[kcud1]}" ]]; then
  bindkey -M emacs "${terminfo[kcud1]}" down-line-or-beginning-search
fi

bindkey -M emacs '^[[1;5C' forward-word
bindkey -M emacs '^[[1;5D' backward-word

bindkey '^R' history-incremental-search-backward

if [ -d ~/.local/share/antidote ]; then
	source ~/.local/share/antidote/antidote.zsh
	antidote load $HOME/.cfg/zsh_plugins.txt
fi
