#!/bin/bash

export ZSH="$HOME/.oh-my-zsh"

DISABLE_AUTO_UPDATE="true"

plugins=(
	git 
	zsh-autosuggestions
	zsh-syntax-highlighting
	yarn
	fzf-tab
)

source "$ZSH/oh-my-zsh.sh"

autoload zmv
bindkey -s '^z' '^Qfg^M'
bindkey -s '^[l' '^Qls^M'
bindkey '^ ' autosuggest-accept
bindkey '^[e' edit-command-line

HISTDUP=erase

setopt sharehistory
setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt hist_ignore_dups
setopt hist_find_no_dups

