#!/bin/bash

export FZF_DEFAULT_COMMAND='ag --hidden -g ""'
export FZF_CTRL_R_OPTS='--sort --exact'
export FZF_DEFAULT_OPTS='
    --reverse
    --height 40%
    --color fg:7,bg:-1,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1,gutter:-1
'
